/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

pub const GHOSTTY_SUCCESS: u32 = 0;
pub type ghostty_app_t = *mut ::std::os::raw::c_void;
pub type ghostty_config_t = *mut ::std::os::raw::c_void;
pub type ghostty_surface_t = *mut ::std::os::raw::c_void;
pub type ghostty_inspector_t = *mut ::std::os::raw::c_void;
pub const ghostty_platform_e_GHOSTTY_PLATFORM_INVALID: ghostty_platform_e = 0;
pub const ghostty_platform_e_GHOSTTY_PLATFORM_MACOS: ghostty_platform_e = 1;
pub const ghostty_platform_e_GHOSTTY_PLATFORM_IOS: ghostty_platform_e = 2;
pub type ghostty_platform_e = ::std::os::raw::c_uint;
pub const ghostty_clipboard_e_GHOSTTY_CLIPBOARD_STANDARD: ghostty_clipboard_e = 0;
pub const ghostty_clipboard_e_GHOSTTY_CLIPBOARD_SELECTION: ghostty_clipboard_e = 1;
pub type ghostty_clipboard_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_clipboard_content_s {
    pub mime: *const ::std::os::raw::c_char,
    pub data: *const ::std::os::raw::c_char,
}
pub const ghostty_clipboard_request_e_GHOSTTY_CLIPBOARD_REQUEST_PASTE: ghostty_clipboard_request_e =
    0;
pub const ghostty_clipboard_request_e_GHOSTTY_CLIPBOARD_REQUEST_OSC_52_READ:
    ghostty_clipboard_request_e = 1;
pub const ghostty_clipboard_request_e_GHOSTTY_CLIPBOARD_REQUEST_OSC_52_WRITE:
    ghostty_clipboard_request_e = 2;
pub type ghostty_clipboard_request_e = ::std::os::raw::c_uint;
pub const ghostty_input_mouse_state_e_GHOSTTY_MOUSE_RELEASE: ghostty_input_mouse_state_e = 0;
pub const ghostty_input_mouse_state_e_GHOSTTY_MOUSE_PRESS: ghostty_input_mouse_state_e = 1;
pub type ghostty_input_mouse_state_e = ::std::os::raw::c_uint;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_UNKNOWN: ghostty_input_mouse_button_e = 0;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_LEFT: ghostty_input_mouse_button_e = 1;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_RIGHT: ghostty_input_mouse_button_e = 2;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_MIDDLE: ghostty_input_mouse_button_e = 3;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_FOUR: ghostty_input_mouse_button_e = 4;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_FIVE: ghostty_input_mouse_button_e = 5;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_SIX: ghostty_input_mouse_button_e = 6;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_SEVEN: ghostty_input_mouse_button_e = 7;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_EIGHT: ghostty_input_mouse_button_e = 8;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_NINE: ghostty_input_mouse_button_e = 9;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_TEN: ghostty_input_mouse_button_e = 10;
pub const ghostty_input_mouse_button_e_GHOSTTY_MOUSE_ELEVEN: ghostty_input_mouse_button_e = 11;
pub type ghostty_input_mouse_button_e = ::std::os::raw::c_uint;
pub const ghostty_input_mouse_momentum_e_GHOSTTY_MOUSE_MOMENTUM_NONE:
    ghostty_input_mouse_momentum_e = 0;
pub const ghostty_input_mouse_momentum_e_GHOSTTY_MOUSE_MOMENTUM_BEGAN:
    ghostty_input_mouse_momentum_e = 1;
pub const ghostty_input_mouse_momentum_e_GHOSTTY_MOUSE_MOMENTUM_STATIONARY:
    ghostty_input_mouse_momentum_e = 2;
pub const ghostty_input_mouse_momentum_e_GHOSTTY_MOUSE_MOMENTUM_CHANGED:
    ghostty_input_mouse_momentum_e = 3;
pub const ghostty_input_mouse_momentum_e_GHOSTTY_MOUSE_MOMENTUM_ENDED:
    ghostty_input_mouse_momentum_e = 4;
pub const ghostty_input_mouse_momentum_e_GHOSTTY_MOUSE_MOMENTUM_CANCELLED:
    ghostty_input_mouse_momentum_e = 5;
pub const ghostty_input_mouse_momentum_e_GHOSTTY_MOUSE_MOMENTUM_MAY_BEGIN:
    ghostty_input_mouse_momentum_e = 6;
pub type ghostty_input_mouse_momentum_e = ::std::os::raw::c_uint;
pub const ghostty_color_scheme_e_GHOSTTY_COLOR_SCHEME_LIGHT: ghostty_color_scheme_e = 0;
pub const ghostty_color_scheme_e_GHOSTTY_COLOR_SCHEME_DARK: ghostty_color_scheme_e = 1;
pub type ghostty_color_scheme_e = ::std::os::raw::c_uint;
pub type ghostty_input_scroll_mods_t = ::std::os::raw::c_int;
pub const ghostty_input_mods_e_GHOSTTY_MODS_NONE: ghostty_input_mods_e = 0;
pub const ghostty_input_mods_e_GHOSTTY_MODS_SHIFT: ghostty_input_mods_e = 1;
pub const ghostty_input_mods_e_GHOSTTY_MODS_CTRL: ghostty_input_mods_e = 2;
pub const ghostty_input_mods_e_GHOSTTY_MODS_ALT: ghostty_input_mods_e = 4;
pub const ghostty_input_mods_e_GHOSTTY_MODS_SUPER: ghostty_input_mods_e = 8;
pub const ghostty_input_mods_e_GHOSTTY_MODS_CAPS: ghostty_input_mods_e = 16;
pub const ghostty_input_mods_e_GHOSTTY_MODS_NUM: ghostty_input_mods_e = 32;
pub const ghostty_input_mods_e_GHOSTTY_MODS_SHIFT_RIGHT: ghostty_input_mods_e = 64;
pub const ghostty_input_mods_e_GHOSTTY_MODS_CTRL_RIGHT: ghostty_input_mods_e = 128;
pub const ghostty_input_mods_e_GHOSTTY_MODS_ALT_RIGHT: ghostty_input_mods_e = 256;
pub const ghostty_input_mods_e_GHOSTTY_MODS_SUPER_RIGHT: ghostty_input_mods_e = 512;
pub type ghostty_input_mods_e = ::std::os::raw::c_uint;
pub const ghostty_binding_flags_e_GHOSTTY_BINDING_FLAGS_CONSUMED: ghostty_binding_flags_e = 1;
pub const ghostty_binding_flags_e_GHOSTTY_BINDING_FLAGS_ALL: ghostty_binding_flags_e = 2;
pub const ghostty_binding_flags_e_GHOSTTY_BINDING_FLAGS_GLOBAL: ghostty_binding_flags_e = 4;
pub const ghostty_binding_flags_e_GHOSTTY_BINDING_FLAGS_PERFORMABLE: ghostty_binding_flags_e = 8;
pub type ghostty_binding_flags_e = ::std::os::raw::c_uint;
pub const ghostty_input_action_e_GHOSTTY_ACTION_RELEASE: ghostty_input_action_e = 0;
pub const ghostty_input_action_e_GHOSTTY_ACTION_PRESS: ghostty_input_action_e = 1;
pub const ghostty_input_action_e_GHOSTTY_ACTION_REPEAT: ghostty_input_action_e = 2;
pub type ghostty_input_action_e = ::std::os::raw::c_uint;
pub const ghostty_input_key_e_GHOSTTY_KEY_UNIDENTIFIED: ghostty_input_key_e = 0;
pub const ghostty_input_key_e_GHOSTTY_KEY_BACKQUOTE: ghostty_input_key_e = 1;
pub const ghostty_input_key_e_GHOSTTY_KEY_BACKSLASH: ghostty_input_key_e = 2;
pub const ghostty_input_key_e_GHOSTTY_KEY_BRACKET_LEFT: ghostty_input_key_e = 3;
pub const ghostty_input_key_e_GHOSTTY_KEY_BRACKET_RIGHT: ghostty_input_key_e = 4;
pub const ghostty_input_key_e_GHOSTTY_KEY_COMMA: ghostty_input_key_e = 5;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_0: ghostty_input_key_e = 6;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_1: ghostty_input_key_e = 7;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_2: ghostty_input_key_e = 8;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_3: ghostty_input_key_e = 9;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_4: ghostty_input_key_e = 10;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_5: ghostty_input_key_e = 11;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_6: ghostty_input_key_e = 12;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_7: ghostty_input_key_e = 13;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_8: ghostty_input_key_e = 14;
pub const ghostty_input_key_e_GHOSTTY_KEY_DIGIT_9: ghostty_input_key_e = 15;
pub const ghostty_input_key_e_GHOSTTY_KEY_EQUAL: ghostty_input_key_e = 16;
pub const ghostty_input_key_e_GHOSTTY_KEY_INTL_BACKSLASH: ghostty_input_key_e = 17;
pub const ghostty_input_key_e_GHOSTTY_KEY_INTL_RO: ghostty_input_key_e = 18;
pub const ghostty_input_key_e_GHOSTTY_KEY_INTL_YEN: ghostty_input_key_e = 19;
pub const ghostty_input_key_e_GHOSTTY_KEY_A: ghostty_input_key_e = 20;
pub const ghostty_input_key_e_GHOSTTY_KEY_B: ghostty_input_key_e = 21;
pub const ghostty_input_key_e_GHOSTTY_KEY_C: ghostty_input_key_e = 22;
pub const ghostty_input_key_e_GHOSTTY_KEY_D: ghostty_input_key_e = 23;
pub const ghostty_input_key_e_GHOSTTY_KEY_E: ghostty_input_key_e = 24;
pub const ghostty_input_key_e_GHOSTTY_KEY_F: ghostty_input_key_e = 25;
pub const ghostty_input_key_e_GHOSTTY_KEY_G: ghostty_input_key_e = 26;
pub const ghostty_input_key_e_GHOSTTY_KEY_H: ghostty_input_key_e = 27;
pub const ghostty_input_key_e_GHOSTTY_KEY_I: ghostty_input_key_e = 28;
pub const ghostty_input_key_e_GHOSTTY_KEY_J: ghostty_input_key_e = 29;
pub const ghostty_input_key_e_GHOSTTY_KEY_K: ghostty_input_key_e = 30;
pub const ghostty_input_key_e_GHOSTTY_KEY_L: ghostty_input_key_e = 31;
pub const ghostty_input_key_e_GHOSTTY_KEY_M: ghostty_input_key_e = 32;
pub const ghostty_input_key_e_GHOSTTY_KEY_N: ghostty_input_key_e = 33;
pub const ghostty_input_key_e_GHOSTTY_KEY_O: ghostty_input_key_e = 34;
pub const ghostty_input_key_e_GHOSTTY_KEY_P: ghostty_input_key_e = 35;
pub const ghostty_input_key_e_GHOSTTY_KEY_Q: ghostty_input_key_e = 36;
pub const ghostty_input_key_e_GHOSTTY_KEY_R: ghostty_input_key_e = 37;
pub const ghostty_input_key_e_GHOSTTY_KEY_S: ghostty_input_key_e = 38;
pub const ghostty_input_key_e_GHOSTTY_KEY_T: ghostty_input_key_e = 39;
pub const ghostty_input_key_e_GHOSTTY_KEY_U: ghostty_input_key_e = 40;
pub const ghostty_input_key_e_GHOSTTY_KEY_V: ghostty_input_key_e = 41;
pub const ghostty_input_key_e_GHOSTTY_KEY_W: ghostty_input_key_e = 42;
pub const ghostty_input_key_e_GHOSTTY_KEY_X: ghostty_input_key_e = 43;
pub const ghostty_input_key_e_GHOSTTY_KEY_Y: ghostty_input_key_e = 44;
pub const ghostty_input_key_e_GHOSTTY_KEY_Z: ghostty_input_key_e = 45;
pub const ghostty_input_key_e_GHOSTTY_KEY_MINUS: ghostty_input_key_e = 46;
pub const ghostty_input_key_e_GHOSTTY_KEY_PERIOD: ghostty_input_key_e = 47;
pub const ghostty_input_key_e_GHOSTTY_KEY_QUOTE: ghostty_input_key_e = 48;
pub const ghostty_input_key_e_GHOSTTY_KEY_SEMICOLON: ghostty_input_key_e = 49;
pub const ghostty_input_key_e_GHOSTTY_KEY_SLASH: ghostty_input_key_e = 50;
pub const ghostty_input_key_e_GHOSTTY_KEY_ALT_LEFT: ghostty_input_key_e = 51;
pub const ghostty_input_key_e_GHOSTTY_KEY_ALT_RIGHT: ghostty_input_key_e = 52;
pub const ghostty_input_key_e_GHOSTTY_KEY_BACKSPACE: ghostty_input_key_e = 53;
pub const ghostty_input_key_e_GHOSTTY_KEY_CAPS_LOCK: ghostty_input_key_e = 54;
pub const ghostty_input_key_e_GHOSTTY_KEY_CONTEXT_MENU: ghostty_input_key_e = 55;
pub const ghostty_input_key_e_GHOSTTY_KEY_CONTROL_LEFT: ghostty_input_key_e = 56;
pub const ghostty_input_key_e_GHOSTTY_KEY_CONTROL_RIGHT: ghostty_input_key_e = 57;
pub const ghostty_input_key_e_GHOSTTY_KEY_ENTER: ghostty_input_key_e = 58;
pub const ghostty_input_key_e_GHOSTTY_KEY_META_LEFT: ghostty_input_key_e = 59;
pub const ghostty_input_key_e_GHOSTTY_KEY_META_RIGHT: ghostty_input_key_e = 60;
pub const ghostty_input_key_e_GHOSTTY_KEY_SHIFT_LEFT: ghostty_input_key_e = 61;
pub const ghostty_input_key_e_GHOSTTY_KEY_SHIFT_RIGHT: ghostty_input_key_e = 62;
pub const ghostty_input_key_e_GHOSTTY_KEY_SPACE: ghostty_input_key_e = 63;
pub const ghostty_input_key_e_GHOSTTY_KEY_TAB: ghostty_input_key_e = 64;
pub const ghostty_input_key_e_GHOSTTY_KEY_CONVERT: ghostty_input_key_e = 65;
pub const ghostty_input_key_e_GHOSTTY_KEY_KANA_MODE: ghostty_input_key_e = 66;
pub const ghostty_input_key_e_GHOSTTY_KEY_NON_CONVERT: ghostty_input_key_e = 67;
pub const ghostty_input_key_e_GHOSTTY_KEY_DELETE: ghostty_input_key_e = 68;
pub const ghostty_input_key_e_GHOSTTY_KEY_END: ghostty_input_key_e = 69;
pub const ghostty_input_key_e_GHOSTTY_KEY_HELP: ghostty_input_key_e = 70;
pub const ghostty_input_key_e_GHOSTTY_KEY_HOME: ghostty_input_key_e = 71;
pub const ghostty_input_key_e_GHOSTTY_KEY_INSERT: ghostty_input_key_e = 72;
pub const ghostty_input_key_e_GHOSTTY_KEY_PAGE_DOWN: ghostty_input_key_e = 73;
pub const ghostty_input_key_e_GHOSTTY_KEY_PAGE_UP: ghostty_input_key_e = 74;
pub const ghostty_input_key_e_GHOSTTY_KEY_ARROW_DOWN: ghostty_input_key_e = 75;
pub const ghostty_input_key_e_GHOSTTY_KEY_ARROW_LEFT: ghostty_input_key_e = 76;
pub const ghostty_input_key_e_GHOSTTY_KEY_ARROW_RIGHT: ghostty_input_key_e = 77;
pub const ghostty_input_key_e_GHOSTTY_KEY_ARROW_UP: ghostty_input_key_e = 78;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUM_LOCK: ghostty_input_key_e = 79;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_0: ghostty_input_key_e = 80;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_1: ghostty_input_key_e = 81;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_2: ghostty_input_key_e = 82;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_3: ghostty_input_key_e = 83;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_4: ghostty_input_key_e = 84;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_5: ghostty_input_key_e = 85;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_6: ghostty_input_key_e = 86;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_7: ghostty_input_key_e = 87;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_8: ghostty_input_key_e = 88;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_9: ghostty_input_key_e = 89;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_ADD: ghostty_input_key_e = 90;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_BACKSPACE: ghostty_input_key_e = 91;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_CLEAR: ghostty_input_key_e = 92;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_CLEAR_ENTRY: ghostty_input_key_e = 93;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_COMMA: ghostty_input_key_e = 94;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_DECIMAL: ghostty_input_key_e = 95;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_DIVIDE: ghostty_input_key_e = 96;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_ENTER: ghostty_input_key_e = 97;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_EQUAL: ghostty_input_key_e = 98;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_MEMORY_ADD: ghostty_input_key_e = 99;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_MEMORY_CLEAR: ghostty_input_key_e = 100;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_MEMORY_RECALL: ghostty_input_key_e = 101;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_MEMORY_STORE: ghostty_input_key_e = 102;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_MEMORY_SUBTRACT: ghostty_input_key_e = 103;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_MULTIPLY: ghostty_input_key_e = 104;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_PAREN_LEFT: ghostty_input_key_e = 105;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_PAREN_RIGHT: ghostty_input_key_e = 106;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_SUBTRACT: ghostty_input_key_e = 107;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_SEPARATOR: ghostty_input_key_e = 108;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_UP: ghostty_input_key_e = 109;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_DOWN: ghostty_input_key_e = 110;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_RIGHT: ghostty_input_key_e = 111;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_LEFT: ghostty_input_key_e = 112;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_BEGIN: ghostty_input_key_e = 113;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_HOME: ghostty_input_key_e = 114;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_END: ghostty_input_key_e = 115;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_INSERT: ghostty_input_key_e = 116;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_DELETE: ghostty_input_key_e = 117;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_PAGE_UP: ghostty_input_key_e = 118;
pub const ghostty_input_key_e_GHOSTTY_KEY_NUMPAD_PAGE_DOWN: ghostty_input_key_e = 119;
pub const ghostty_input_key_e_GHOSTTY_KEY_ESCAPE: ghostty_input_key_e = 120;
pub const ghostty_input_key_e_GHOSTTY_KEY_F1: ghostty_input_key_e = 121;
pub const ghostty_input_key_e_GHOSTTY_KEY_F2: ghostty_input_key_e = 122;
pub const ghostty_input_key_e_GHOSTTY_KEY_F3: ghostty_input_key_e = 123;
pub const ghostty_input_key_e_GHOSTTY_KEY_F4: ghostty_input_key_e = 124;
pub const ghostty_input_key_e_GHOSTTY_KEY_F5: ghostty_input_key_e = 125;
pub const ghostty_input_key_e_GHOSTTY_KEY_F6: ghostty_input_key_e = 126;
pub const ghostty_input_key_e_GHOSTTY_KEY_F7: ghostty_input_key_e = 127;
pub const ghostty_input_key_e_GHOSTTY_KEY_F8: ghostty_input_key_e = 128;
pub const ghostty_input_key_e_GHOSTTY_KEY_F9: ghostty_input_key_e = 129;
pub const ghostty_input_key_e_GHOSTTY_KEY_F10: ghostty_input_key_e = 130;
pub const ghostty_input_key_e_GHOSTTY_KEY_F11: ghostty_input_key_e = 131;
pub const ghostty_input_key_e_GHOSTTY_KEY_F12: ghostty_input_key_e = 132;
pub const ghostty_input_key_e_GHOSTTY_KEY_F13: ghostty_input_key_e = 133;
pub const ghostty_input_key_e_GHOSTTY_KEY_F14: ghostty_input_key_e = 134;
pub const ghostty_input_key_e_GHOSTTY_KEY_F15: ghostty_input_key_e = 135;
pub const ghostty_input_key_e_GHOSTTY_KEY_F16: ghostty_input_key_e = 136;
pub const ghostty_input_key_e_GHOSTTY_KEY_F17: ghostty_input_key_e = 137;
pub const ghostty_input_key_e_GHOSTTY_KEY_F18: ghostty_input_key_e = 138;
pub const ghostty_input_key_e_GHOSTTY_KEY_F19: ghostty_input_key_e = 139;
pub const ghostty_input_key_e_GHOSTTY_KEY_F20: ghostty_input_key_e = 140;
pub const ghostty_input_key_e_GHOSTTY_KEY_F21: ghostty_input_key_e = 141;
pub const ghostty_input_key_e_GHOSTTY_KEY_F22: ghostty_input_key_e = 142;
pub const ghostty_input_key_e_GHOSTTY_KEY_F23: ghostty_input_key_e = 143;
pub const ghostty_input_key_e_GHOSTTY_KEY_F24: ghostty_input_key_e = 144;
pub const ghostty_input_key_e_GHOSTTY_KEY_F25: ghostty_input_key_e = 145;
pub const ghostty_input_key_e_GHOSTTY_KEY_FN: ghostty_input_key_e = 146;
pub const ghostty_input_key_e_GHOSTTY_KEY_FN_LOCK: ghostty_input_key_e = 147;
pub const ghostty_input_key_e_GHOSTTY_KEY_PRINT_SCREEN: ghostty_input_key_e = 148;
pub const ghostty_input_key_e_GHOSTTY_KEY_SCROLL_LOCK: ghostty_input_key_e = 149;
pub const ghostty_input_key_e_GHOSTTY_KEY_PAUSE: ghostty_input_key_e = 150;
pub const ghostty_input_key_e_GHOSTTY_KEY_BROWSER_BACK: ghostty_input_key_e = 151;
pub const ghostty_input_key_e_GHOSTTY_KEY_BROWSER_FAVORITES: ghostty_input_key_e = 152;
pub const ghostty_input_key_e_GHOSTTY_KEY_BROWSER_FORWARD: ghostty_input_key_e = 153;
pub const ghostty_input_key_e_GHOSTTY_KEY_BROWSER_HOME: ghostty_input_key_e = 154;
pub const ghostty_input_key_e_GHOSTTY_KEY_BROWSER_REFRESH: ghostty_input_key_e = 155;
pub const ghostty_input_key_e_GHOSTTY_KEY_BROWSER_SEARCH: ghostty_input_key_e = 156;
pub const ghostty_input_key_e_GHOSTTY_KEY_BROWSER_STOP: ghostty_input_key_e = 157;
pub const ghostty_input_key_e_GHOSTTY_KEY_EJECT: ghostty_input_key_e = 158;
pub const ghostty_input_key_e_GHOSTTY_KEY_LAUNCH_APP_1: ghostty_input_key_e = 159;
pub const ghostty_input_key_e_GHOSTTY_KEY_LAUNCH_APP_2: ghostty_input_key_e = 160;
pub const ghostty_input_key_e_GHOSTTY_KEY_LAUNCH_MAIL: ghostty_input_key_e = 161;
pub const ghostty_input_key_e_GHOSTTY_KEY_MEDIA_PLAY_PAUSE: ghostty_input_key_e = 162;
pub const ghostty_input_key_e_GHOSTTY_KEY_MEDIA_SELECT: ghostty_input_key_e = 163;
pub const ghostty_input_key_e_GHOSTTY_KEY_MEDIA_STOP: ghostty_input_key_e = 164;
pub const ghostty_input_key_e_GHOSTTY_KEY_MEDIA_TRACK_NEXT: ghostty_input_key_e = 165;
pub const ghostty_input_key_e_GHOSTTY_KEY_MEDIA_TRACK_PREVIOUS: ghostty_input_key_e = 166;
pub const ghostty_input_key_e_GHOSTTY_KEY_POWER: ghostty_input_key_e = 167;
pub const ghostty_input_key_e_GHOSTTY_KEY_SLEEP: ghostty_input_key_e = 168;
pub const ghostty_input_key_e_GHOSTTY_KEY_AUDIO_VOLUME_DOWN: ghostty_input_key_e = 169;
pub const ghostty_input_key_e_GHOSTTY_KEY_AUDIO_VOLUME_MUTE: ghostty_input_key_e = 170;
pub const ghostty_input_key_e_GHOSTTY_KEY_AUDIO_VOLUME_UP: ghostty_input_key_e = 171;
pub const ghostty_input_key_e_GHOSTTY_KEY_WAKE_UP: ghostty_input_key_e = 172;
pub const ghostty_input_key_e_GHOSTTY_KEY_COPY: ghostty_input_key_e = 173;
pub const ghostty_input_key_e_GHOSTTY_KEY_CUT: ghostty_input_key_e = 174;
pub const ghostty_input_key_e_GHOSTTY_KEY_PASTE: ghostty_input_key_e = 175;
pub type ghostty_input_key_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_input_key_s {
    pub action: ghostty_input_action_e,
    pub mods: ghostty_input_mods_e,
    pub consumed_mods: ghostty_input_mods_e,
    pub keycode: u32,
    pub text: *const ::std::os::raw::c_char,
    pub unshifted_codepoint: u32,
    pub composing: bool,
}
pub const ghostty_input_trigger_tag_e_GHOSTTY_TRIGGER_PHYSICAL: ghostty_input_trigger_tag_e = 0;
pub const ghostty_input_trigger_tag_e_GHOSTTY_TRIGGER_UNICODE: ghostty_input_trigger_tag_e = 1;
pub const ghostty_input_trigger_tag_e_GHOSTTY_TRIGGER_CATCH_ALL: ghostty_input_trigger_tag_e = 2;
pub type ghostty_input_trigger_tag_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_input_trigger_key_u {
    pub translated: ghostty_input_key_e,
    pub physical: ghostty_input_key_e,
    pub unicode: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_input_trigger_s {
    pub tag: ghostty_input_trigger_tag_e,
    pub key: ghostty_input_trigger_key_u,
    pub mods: ghostty_input_mods_e,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_command_s {
    pub action_key: *const ::std::os::raw::c_char,
    pub action: *const ::std::os::raw::c_char,
    pub title: *const ::std::os::raw::c_char,
    pub description: *const ::std::os::raw::c_char,
}
pub const ghostty_build_mode_e_GHOSTTY_BUILD_MODE_DEBUG: ghostty_build_mode_e = 0;
pub const ghostty_build_mode_e_GHOSTTY_BUILD_MODE_RELEASE_SAFE: ghostty_build_mode_e = 1;
pub const ghostty_build_mode_e_GHOSTTY_BUILD_MODE_RELEASE_FAST: ghostty_build_mode_e = 2;
pub const ghostty_build_mode_e_GHOSTTY_BUILD_MODE_RELEASE_SMALL: ghostty_build_mode_e = 3;
pub type ghostty_build_mode_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_info_s {
    pub build_mode: ghostty_build_mode_e,
    pub version: *const ::std::os::raw::c_char,
    pub version_len: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_diagnostic_s {
    pub message: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_string_s {
    pub ptr: *const ::std::os::raw::c_char,
    pub len: usize,
    pub sentinel: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_text_s {
    pub tl_px_x: f64,
    pub tl_px_y: f64,
    pub offset_start: u32,
    pub offset_len: u32,
    pub text: *const ::std::os::raw::c_char,
    pub text_len: usize,
}
pub const ghostty_point_tag_e_GHOSTTY_POINT_ACTIVE: ghostty_point_tag_e = 0;
pub const ghostty_point_tag_e_GHOSTTY_POINT_VIEWPORT: ghostty_point_tag_e = 1;
pub const ghostty_point_tag_e_GHOSTTY_POINT_SCREEN: ghostty_point_tag_e = 2;
pub const ghostty_point_tag_e_GHOSTTY_POINT_SURFACE: ghostty_point_tag_e = 3;
pub type ghostty_point_tag_e = ::std::os::raw::c_uint;
pub const ghostty_point_coord_e_GHOSTTY_POINT_COORD_EXACT: ghostty_point_coord_e = 0;
pub const ghostty_point_coord_e_GHOSTTY_POINT_COORD_TOP_LEFT: ghostty_point_coord_e = 1;
pub const ghostty_point_coord_e_GHOSTTY_POINT_COORD_BOTTOM_RIGHT: ghostty_point_coord_e = 2;
pub type ghostty_point_coord_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_point_s {
    pub tag: ghostty_point_tag_e,
    pub coord: ghostty_point_coord_e,
    pub x: u32,
    pub y: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_selection_s {
    pub top_left: ghostty_point_s,
    pub bottom_right: ghostty_point_s,
    pub rectangle: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_env_var_s {
    pub key: *const ::std::os::raw::c_char,
    pub value: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_platform_macos_s {
    pub nsview: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_platform_ios_s {
    pub uiview: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_platform_u {
    pub macos: ghostty_platform_macos_s,
    pub ios: ghostty_platform_ios_s,
}
pub const ghostty_surface_context_e_GHOSTTY_SURFACE_CONTEXT_WINDOW: ghostty_surface_context_e = 0;
pub const ghostty_surface_context_e_GHOSTTY_SURFACE_CONTEXT_TAB: ghostty_surface_context_e = 1;
pub const ghostty_surface_context_e_GHOSTTY_SURFACE_CONTEXT_SPLIT: ghostty_surface_context_e = 2;
pub type ghostty_surface_context_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_surface_config_s {
    pub platform_tag: ghostty_platform_e,
    pub platform: ghostty_platform_u,
    pub userdata: *mut ::std::os::raw::c_void,
    pub scale_factor: f64,
    pub font_size: f32,
    pub working_directory: *const ::std::os::raw::c_char,
    pub command: *const ::std::os::raw::c_char,
    pub env_vars: *mut ghostty_env_var_s,
    pub env_var_count: usize,
    pub initial_input: *const ::std::os::raw::c_char,
    pub wait_after_command: bool,
    pub context: ghostty_surface_context_e,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_surface_size_s {
    pub columns: u16,
    pub rows: u16,
    pub width_px: u32,
    pub height_px: u32,
    pub cell_width_px: u32,
    pub cell_height_px: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_config_path_s {
    pub path: *const ::std::os::raw::c_char,
    pub optional: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_config_color_s {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_config_color_list_s {
    pub colors: *const ghostty_config_color_s,
    pub len: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_config_command_list_s {
    pub commands: *const ghostty_command_s,
    pub len: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_config_palette_s {
    pub colors: [ghostty_config_color_s; 256usize],
}
pub const ghostty_quick_terminal_size_tag_e_GHOSTTY_QUICK_TERMINAL_SIZE_NONE:
    ghostty_quick_terminal_size_tag_e = 0;
pub const ghostty_quick_terminal_size_tag_e_GHOSTTY_QUICK_TERMINAL_SIZE_PERCENTAGE:
    ghostty_quick_terminal_size_tag_e = 1;
pub const ghostty_quick_terminal_size_tag_e_GHOSTTY_QUICK_TERMINAL_SIZE_PIXELS:
    ghostty_quick_terminal_size_tag_e = 2;
pub type ghostty_quick_terminal_size_tag_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_quick_terminal_size_value_u {
    pub percentage: f32,
    pub pixels: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_quick_terminal_size_s {
    pub tag: ghostty_quick_terminal_size_tag_e,
    pub value: ghostty_quick_terminal_size_value_u,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_config_quick_terminal_size_s {
    pub primary: ghostty_quick_terminal_size_s,
    pub secondary: ghostty_quick_terminal_size_s,
}
pub const ghostty_config_fullscreen_e_GHOSTTY_CONFIG_FULLSCREEN_FALSE: ghostty_config_fullscreen_e =
    0;
pub const ghostty_config_fullscreen_e_GHOSTTY_CONFIG_FULLSCREEN_TRUE: ghostty_config_fullscreen_e =
    1;
pub const ghostty_config_fullscreen_e_GHOSTTY_CONFIG_FULLSCREEN_NON_NATIVE:
    ghostty_config_fullscreen_e = 2;
pub const ghostty_config_fullscreen_e_GHOSTTY_CONFIG_FULLSCREEN_NON_NATIVE_VISIBLE_MENU:
    ghostty_config_fullscreen_e = 3;
pub const ghostty_config_fullscreen_e_GHOSTTY_CONFIG_FULLSCREEN_NON_NATIVE_PADDED_NOTCH:
    ghostty_config_fullscreen_e = 4;
pub type ghostty_config_fullscreen_e = ::std::os::raw::c_uint;
pub const ghostty_target_tag_e_GHOSTTY_TARGET_APP: ghostty_target_tag_e = 0;
pub const ghostty_target_tag_e_GHOSTTY_TARGET_SURFACE: ghostty_target_tag_e = 1;
pub type ghostty_target_tag_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_target_u {
    pub surface: ghostty_surface_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_target_s {
    pub tag: ghostty_target_tag_e,
    pub target: ghostty_target_u,
}
pub const ghostty_action_split_direction_e_GHOSTTY_SPLIT_DIRECTION_RIGHT:
    ghostty_action_split_direction_e = 0;
pub const ghostty_action_split_direction_e_GHOSTTY_SPLIT_DIRECTION_DOWN:
    ghostty_action_split_direction_e = 1;
pub const ghostty_action_split_direction_e_GHOSTTY_SPLIT_DIRECTION_LEFT:
    ghostty_action_split_direction_e = 2;
pub const ghostty_action_split_direction_e_GHOSTTY_SPLIT_DIRECTION_UP:
    ghostty_action_split_direction_e = 3;
pub type ghostty_action_split_direction_e = ::std::os::raw::c_uint;
pub const ghostty_action_goto_split_e_GHOSTTY_GOTO_SPLIT_PREVIOUS: ghostty_action_goto_split_e = 0;
pub const ghostty_action_goto_split_e_GHOSTTY_GOTO_SPLIT_NEXT: ghostty_action_goto_split_e = 1;
pub const ghostty_action_goto_split_e_GHOSTTY_GOTO_SPLIT_UP: ghostty_action_goto_split_e = 2;
pub const ghostty_action_goto_split_e_GHOSTTY_GOTO_SPLIT_LEFT: ghostty_action_goto_split_e = 3;
pub const ghostty_action_goto_split_e_GHOSTTY_GOTO_SPLIT_DOWN: ghostty_action_goto_split_e = 4;
pub const ghostty_action_goto_split_e_GHOSTTY_GOTO_SPLIT_RIGHT: ghostty_action_goto_split_e = 5;
pub type ghostty_action_goto_split_e = ::std::os::raw::c_uint;
pub const ghostty_action_goto_window_e_GHOSTTY_GOTO_WINDOW_PREVIOUS: ghostty_action_goto_window_e =
    0;
pub const ghostty_action_goto_window_e_GHOSTTY_GOTO_WINDOW_NEXT: ghostty_action_goto_window_e = 1;
pub type ghostty_action_goto_window_e = ::std::os::raw::c_uint;
pub const ghostty_action_resize_split_direction_e_GHOSTTY_RESIZE_SPLIT_UP:
    ghostty_action_resize_split_direction_e = 0;
pub const ghostty_action_resize_split_direction_e_GHOSTTY_RESIZE_SPLIT_DOWN:
    ghostty_action_resize_split_direction_e = 1;
pub const ghostty_action_resize_split_direction_e_GHOSTTY_RESIZE_SPLIT_LEFT:
    ghostty_action_resize_split_direction_e = 2;
pub const ghostty_action_resize_split_direction_e_GHOSTTY_RESIZE_SPLIT_RIGHT:
    ghostty_action_resize_split_direction_e = 3;
pub type ghostty_action_resize_split_direction_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_resize_split_s {
    pub amount: u16,
    pub direction: ghostty_action_resize_split_direction_e,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_move_tab_s {
    pub amount: isize,
}
pub const ghostty_action_goto_tab_e_GHOSTTY_GOTO_TAB_PREVIOUS: ghostty_action_goto_tab_e = -1;
pub const ghostty_action_goto_tab_e_GHOSTTY_GOTO_TAB_NEXT: ghostty_action_goto_tab_e = -2;
pub const ghostty_action_goto_tab_e_GHOSTTY_GOTO_TAB_LAST: ghostty_action_goto_tab_e = -3;
pub type ghostty_action_goto_tab_e = ::std::os::raw::c_int;
pub const ghostty_action_fullscreen_e_GHOSTTY_FULLSCREEN_NATIVE: ghostty_action_fullscreen_e = 0;
pub const ghostty_action_fullscreen_e_GHOSTTY_FULLSCREEN_MACOS_NON_NATIVE:
    ghostty_action_fullscreen_e = 1;
pub const ghostty_action_fullscreen_e_GHOSTTY_FULLSCREEN_MACOS_NON_NATIVE_VISIBLE_MENU:
    ghostty_action_fullscreen_e = 2;
pub const ghostty_action_fullscreen_e_GHOSTTY_FULLSCREEN_MACOS_NON_NATIVE_PADDED_NOTCH:
    ghostty_action_fullscreen_e = 3;
pub type ghostty_action_fullscreen_e = ::std::os::raw::c_uint;
pub const ghostty_action_float_window_e_GHOSTTY_FLOAT_WINDOW_ON: ghostty_action_float_window_e = 0;
pub const ghostty_action_float_window_e_GHOSTTY_FLOAT_WINDOW_OFF: ghostty_action_float_window_e = 1;
pub const ghostty_action_float_window_e_GHOSTTY_FLOAT_WINDOW_TOGGLE: ghostty_action_float_window_e =
    2;
pub type ghostty_action_float_window_e = ::std::os::raw::c_uint;
pub const ghostty_action_secure_input_e_GHOSTTY_SECURE_INPUT_ON: ghostty_action_secure_input_e = 0;
pub const ghostty_action_secure_input_e_GHOSTTY_SECURE_INPUT_OFF: ghostty_action_secure_input_e = 1;
pub const ghostty_action_secure_input_e_GHOSTTY_SECURE_INPUT_TOGGLE: ghostty_action_secure_input_e =
    2;
pub type ghostty_action_secure_input_e = ::std::os::raw::c_uint;
pub const ghostty_action_inspector_e_GHOSTTY_INSPECTOR_TOGGLE: ghostty_action_inspector_e = 0;
pub const ghostty_action_inspector_e_GHOSTTY_INSPECTOR_SHOW: ghostty_action_inspector_e = 1;
pub const ghostty_action_inspector_e_GHOSTTY_INSPECTOR_HIDE: ghostty_action_inspector_e = 2;
pub type ghostty_action_inspector_e = ::std::os::raw::c_uint;
pub const ghostty_action_quit_timer_e_GHOSTTY_QUIT_TIMER_START: ghostty_action_quit_timer_e = 0;
pub const ghostty_action_quit_timer_e_GHOSTTY_QUIT_TIMER_STOP: ghostty_action_quit_timer_e = 1;
pub type ghostty_action_quit_timer_e = ::std::os::raw::c_uint;
pub const ghostty_action_readonly_e_GHOSTTY_READONLY_OFF: ghostty_action_readonly_e = 0;
pub const ghostty_action_readonly_e_GHOSTTY_READONLY_ON: ghostty_action_readonly_e = 1;
pub type ghostty_action_readonly_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_desktop_notification_s {
    pub title: *const ::std::os::raw::c_char,
    pub body: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_set_title_s {
    pub title: *const ::std::os::raw::c_char,
}
pub const ghostty_action_prompt_title_e_GHOSTTY_PROMPT_TITLE_SURFACE:
    ghostty_action_prompt_title_e = 0;
pub const ghostty_action_prompt_title_e_GHOSTTY_PROMPT_TITLE_TAB: ghostty_action_prompt_title_e = 1;
pub type ghostty_action_prompt_title_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_pwd_s {
    pub pwd: *const ::std::os::raw::c_char,
}
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_DEFAULT: ghostty_action_mouse_shape_e =
    0;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_CONTEXT_MENU:
    ghostty_action_mouse_shape_e = 1;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_HELP: ghostty_action_mouse_shape_e = 2;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_POINTER: ghostty_action_mouse_shape_e =
    3;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_PROGRESS: ghostty_action_mouse_shape_e =
    4;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_WAIT: ghostty_action_mouse_shape_e = 5;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_CELL: ghostty_action_mouse_shape_e = 6;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_CROSSHAIR: ghostty_action_mouse_shape_e =
    7;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_TEXT: ghostty_action_mouse_shape_e = 8;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_VERTICAL_TEXT:
    ghostty_action_mouse_shape_e = 9;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_ALIAS: ghostty_action_mouse_shape_e = 10;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_COPY: ghostty_action_mouse_shape_e = 11;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_MOVE: ghostty_action_mouse_shape_e = 12;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_NO_DROP: ghostty_action_mouse_shape_e =
    13;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_NOT_ALLOWED:
    ghostty_action_mouse_shape_e = 14;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_GRAB: ghostty_action_mouse_shape_e = 15;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_GRABBING: ghostty_action_mouse_shape_e =
    16;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_ALL_SCROLL:
    ghostty_action_mouse_shape_e = 17;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_COL_RESIZE:
    ghostty_action_mouse_shape_e = 18;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_ROW_RESIZE:
    ghostty_action_mouse_shape_e = 19;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_N_RESIZE: ghostty_action_mouse_shape_e =
    20;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_E_RESIZE: ghostty_action_mouse_shape_e =
    21;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_S_RESIZE: ghostty_action_mouse_shape_e =
    22;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_W_RESIZE: ghostty_action_mouse_shape_e =
    23;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_NE_RESIZE: ghostty_action_mouse_shape_e =
    24;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_NW_RESIZE: ghostty_action_mouse_shape_e =
    25;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_SE_RESIZE: ghostty_action_mouse_shape_e =
    26;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_SW_RESIZE: ghostty_action_mouse_shape_e =
    27;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_EW_RESIZE: ghostty_action_mouse_shape_e =
    28;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_NS_RESIZE: ghostty_action_mouse_shape_e =
    29;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_NESW_RESIZE:
    ghostty_action_mouse_shape_e = 30;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_NWSE_RESIZE:
    ghostty_action_mouse_shape_e = 31;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_ZOOM_IN: ghostty_action_mouse_shape_e =
    32;
pub const ghostty_action_mouse_shape_e_GHOSTTY_MOUSE_SHAPE_ZOOM_OUT: ghostty_action_mouse_shape_e =
    33;
pub type ghostty_action_mouse_shape_e = ::std::os::raw::c_uint;
pub const ghostty_action_mouse_visibility_e_GHOSTTY_MOUSE_VISIBLE:
    ghostty_action_mouse_visibility_e = 0;
pub const ghostty_action_mouse_visibility_e_GHOSTTY_MOUSE_HIDDEN:
    ghostty_action_mouse_visibility_e = 1;
pub type ghostty_action_mouse_visibility_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_mouse_over_link_s {
    pub url: *const ::std::os::raw::c_char,
    pub len: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_size_limit_s {
    pub min_width: u32,
    pub min_height: u32,
    pub max_width: u32,
    pub max_height: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_initial_size_s {
    pub width: u32,
    pub height: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_cell_size_s {
    pub width: u32,
    pub height: u32,
}
pub const ghostty_action_renderer_health_e_GHOSTTY_RENDERER_HEALTH_HEALTHY:
    ghostty_action_renderer_health_e = 0;
pub const ghostty_action_renderer_health_e_GHOSTTY_RENDERER_HEALTH_UNHEALTHY:
    ghostty_action_renderer_health_e = 1;
pub type ghostty_action_renderer_health_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_action_key_sequence_s {
    pub active: bool,
    pub trigger: ghostty_input_trigger_s,
}
pub const ghostty_action_key_table_tag_e_GHOSTTY_KEY_TABLE_ACTIVATE:
    ghostty_action_key_table_tag_e = 0;
pub const ghostty_action_key_table_tag_e_GHOSTTY_KEY_TABLE_DEACTIVATE:
    ghostty_action_key_table_tag_e = 1;
pub const ghostty_action_key_table_tag_e_GHOSTTY_KEY_TABLE_DEACTIVATE_ALL:
    ghostty_action_key_table_tag_e = 2;
pub type ghostty_action_key_table_tag_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_action_key_table_u {
    pub activate: ghostty_action_key_table_u__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_key_table_u__bindgen_ty_1 {
    pub name: *const ::std::os::raw::c_char,
    pub len: usize,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_action_key_table_s {
    pub tag: ghostty_action_key_table_tag_e,
    pub value: ghostty_action_key_table_u,
}
pub const ghostty_action_color_kind_e_GHOSTTY_ACTION_COLOR_KIND_FOREGROUND:
    ghostty_action_color_kind_e = -1;
pub const ghostty_action_color_kind_e_GHOSTTY_ACTION_COLOR_KIND_BACKGROUND:
    ghostty_action_color_kind_e = -2;
pub const ghostty_action_color_kind_e_GHOSTTY_ACTION_COLOR_KIND_CURSOR:
    ghostty_action_color_kind_e = -3;
pub type ghostty_action_color_kind_e = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_color_change_s {
    pub kind: ghostty_action_color_kind_e,
    pub r: u8,
    pub g: u8,
    pub b: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_config_change_s {
    pub config: ghostty_config_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_reload_config_s {
    pub soft: bool,
}
pub const ghostty_action_open_url_kind_e_GHOSTTY_ACTION_OPEN_URL_KIND_UNKNOWN:
    ghostty_action_open_url_kind_e = 0;
pub const ghostty_action_open_url_kind_e_GHOSTTY_ACTION_OPEN_URL_KIND_TEXT:
    ghostty_action_open_url_kind_e = 1;
pub const ghostty_action_open_url_kind_e_GHOSTTY_ACTION_OPEN_URL_KIND_HTML:
    ghostty_action_open_url_kind_e = 2;
pub type ghostty_action_open_url_kind_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_open_url_s {
    pub kind: ghostty_action_open_url_kind_e,
    pub url: *const ::std::os::raw::c_char,
    pub len: usize,
}
pub const ghostty_action_close_tab_mode_e_GHOSTTY_ACTION_CLOSE_TAB_MODE_THIS:
    ghostty_action_close_tab_mode_e = 0;
pub const ghostty_action_close_tab_mode_e_GHOSTTY_ACTION_CLOSE_TAB_MODE_OTHER:
    ghostty_action_close_tab_mode_e = 1;
pub const ghostty_action_close_tab_mode_e_GHOSTTY_ACTION_CLOSE_TAB_MODE_RIGHT:
    ghostty_action_close_tab_mode_e = 2;
pub type ghostty_action_close_tab_mode_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_surface_message_childexited_s {
    pub exit_code: u32,
    pub timetime_ms: u64,
}
pub const ghostty_action_progress_report_state_e_GHOSTTY_PROGRESS_STATE_REMOVE:
    ghostty_action_progress_report_state_e = 0;
pub const ghostty_action_progress_report_state_e_GHOSTTY_PROGRESS_STATE_SET:
    ghostty_action_progress_report_state_e = 1;
pub const ghostty_action_progress_report_state_e_GHOSTTY_PROGRESS_STATE_ERROR:
    ghostty_action_progress_report_state_e = 2;
pub const ghostty_action_progress_report_state_e_GHOSTTY_PROGRESS_STATE_INDETERMINATE:
    ghostty_action_progress_report_state_e = 3;
pub const ghostty_action_progress_report_state_e_GHOSTTY_PROGRESS_STATE_PAUSE:
    ghostty_action_progress_report_state_e = 4;
pub type ghostty_action_progress_report_state_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_progress_report_s {
    pub state: ghostty_action_progress_report_state_e,
    pub progress: i8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_command_finished_s {
    pub exit_code: i16,
    pub duration: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_start_search_s {
    pub needle: *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_search_total_s {
    pub total: isize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_search_selected_s {
    pub selected: isize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_action_scrollbar_s {
    pub total: u64,
    pub offset: u64,
    pub len: u64,
}
pub const ghostty_action_tag_e_GHOSTTY_ACTION_QUIT: ghostty_action_tag_e = 0;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_NEW_WINDOW: ghostty_action_tag_e = 1;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_NEW_TAB: ghostty_action_tag_e = 2;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_CLOSE_TAB: ghostty_action_tag_e = 3;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_NEW_SPLIT: ghostty_action_tag_e = 4;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_CLOSE_ALL_WINDOWS: ghostty_action_tag_e = 5;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_MAXIMIZE: ghostty_action_tag_e = 6;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_FULLSCREEN: ghostty_action_tag_e = 7;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_TAB_OVERVIEW: ghostty_action_tag_e = 8;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_WINDOW_DECORATIONS: ghostty_action_tag_e = 9;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_QUICK_TERMINAL: ghostty_action_tag_e = 10;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_COMMAND_PALETTE: ghostty_action_tag_e = 11;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_VISIBILITY: ghostty_action_tag_e = 12;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_BACKGROUND_OPACITY: ghostty_action_tag_e = 13;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_MOVE_TAB: ghostty_action_tag_e = 14;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_GOTO_TAB: ghostty_action_tag_e = 15;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_GOTO_SPLIT: ghostty_action_tag_e = 16;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_GOTO_WINDOW: ghostty_action_tag_e = 17;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_RESIZE_SPLIT: ghostty_action_tag_e = 18;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_EQUALIZE_SPLITS: ghostty_action_tag_e = 19;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_TOGGLE_SPLIT_ZOOM: ghostty_action_tag_e = 20;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_PRESENT_TERMINAL: ghostty_action_tag_e = 21;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SIZE_LIMIT: ghostty_action_tag_e = 22;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_RESET_WINDOW_SIZE: ghostty_action_tag_e = 23;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_INITIAL_SIZE: ghostty_action_tag_e = 24;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_CELL_SIZE: ghostty_action_tag_e = 25;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SCROLLBAR: ghostty_action_tag_e = 26;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_RENDER: ghostty_action_tag_e = 27;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_INSPECTOR: ghostty_action_tag_e = 28;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SHOW_GTK_INSPECTOR: ghostty_action_tag_e = 29;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_RENDER_INSPECTOR: ghostty_action_tag_e = 30;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_DESKTOP_NOTIFICATION: ghostty_action_tag_e = 31;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SET_TITLE: ghostty_action_tag_e = 32;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SET_TAB_TITLE: ghostty_action_tag_e = 33;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_PROMPT_TITLE: ghostty_action_tag_e = 34;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_PWD: ghostty_action_tag_e = 35;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_MOUSE_SHAPE: ghostty_action_tag_e = 36;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_MOUSE_VISIBILITY: ghostty_action_tag_e = 37;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_MOUSE_OVER_LINK: ghostty_action_tag_e = 38;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_RENDERER_HEALTH: ghostty_action_tag_e = 39;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_OPEN_CONFIG: ghostty_action_tag_e = 40;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_QUIT_TIMER: ghostty_action_tag_e = 41;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_FLOAT_WINDOW: ghostty_action_tag_e = 42;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SECURE_INPUT: ghostty_action_tag_e = 43;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_KEY_SEQUENCE: ghostty_action_tag_e = 44;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_KEY_TABLE: ghostty_action_tag_e = 45;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_COLOR_CHANGE: ghostty_action_tag_e = 46;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_RELOAD_CONFIG: ghostty_action_tag_e = 47;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_CONFIG_CHANGE: ghostty_action_tag_e = 48;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_CLOSE_WINDOW: ghostty_action_tag_e = 49;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_RING_BELL: ghostty_action_tag_e = 50;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_UNDO: ghostty_action_tag_e = 51;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_REDO: ghostty_action_tag_e = 52;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_CHECK_FOR_UPDATES: ghostty_action_tag_e = 53;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_OPEN_URL: ghostty_action_tag_e = 54;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SHOW_CHILD_EXITED: ghostty_action_tag_e = 55;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_PROGRESS_REPORT: ghostty_action_tag_e = 56;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SHOW_ON_SCREEN_KEYBOARD: ghostty_action_tag_e = 57;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_COMMAND_FINISHED: ghostty_action_tag_e = 58;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_START_SEARCH: ghostty_action_tag_e = 59;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_END_SEARCH: ghostty_action_tag_e = 60;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SEARCH_TOTAL: ghostty_action_tag_e = 61;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_SEARCH_SELECTED: ghostty_action_tag_e = 62;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_READONLY: ghostty_action_tag_e = 63;
pub const ghostty_action_tag_e_GHOSTTY_ACTION_COPY_TITLE_TO_CLIPBOARD: ghostty_action_tag_e = 64;
pub type ghostty_action_tag_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_action_u {
    pub new_split: ghostty_action_split_direction_e,
    pub toggle_fullscreen: ghostty_action_fullscreen_e,
    pub move_tab: ghostty_action_move_tab_s,
    pub goto_tab: ghostty_action_goto_tab_e,
    pub goto_split: ghostty_action_goto_split_e,
    pub goto_window: ghostty_action_goto_window_e,
    pub resize_split: ghostty_action_resize_split_s,
    pub size_limit: ghostty_action_size_limit_s,
    pub initial_size: ghostty_action_initial_size_s,
    pub cell_size: ghostty_action_cell_size_s,
    pub scrollbar: ghostty_action_scrollbar_s,
    pub inspector: ghostty_action_inspector_e,
    pub desktop_notification: ghostty_action_desktop_notification_s,
    pub set_title: ghostty_action_set_title_s,
    pub set_tab_title: ghostty_action_set_title_s,
    pub prompt_title: ghostty_action_prompt_title_e,
    pub pwd: ghostty_action_pwd_s,
    pub mouse_shape: ghostty_action_mouse_shape_e,
    pub mouse_visibility: ghostty_action_mouse_visibility_e,
    pub mouse_over_link: ghostty_action_mouse_over_link_s,
    pub renderer_health: ghostty_action_renderer_health_e,
    pub quit_timer: ghostty_action_quit_timer_e,
    pub float_window: ghostty_action_float_window_e,
    pub secure_input: ghostty_action_secure_input_e,
    pub key_sequence: ghostty_action_key_sequence_s,
    pub key_table: ghostty_action_key_table_s,
    pub color_change: ghostty_action_color_change_s,
    pub reload_config: ghostty_action_reload_config_s,
    pub config_change: ghostty_action_config_change_s,
    pub open_url: ghostty_action_open_url_s,
    pub close_tab_mode: ghostty_action_close_tab_mode_e,
    pub child_exited: ghostty_surface_message_childexited_s,
    pub progress_report: ghostty_action_progress_report_s,
    pub command_finished: ghostty_action_command_finished_s,
    pub start_search: ghostty_action_start_search_s,
    pub search_total: ghostty_action_search_total_s,
    pub search_selected: ghostty_action_search_selected_s,
    pub readonly: ghostty_action_readonly_e,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ghostty_action_s {
    pub tag: ghostty_action_tag_e,
    pub action: ghostty_action_u,
}
pub type ghostty_runtime_wakeup_cb =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
pub type ghostty_runtime_read_clipboard_cb = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: ghostty_clipboard_e,
        arg3: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type ghostty_runtime_confirm_read_clipboard_cb = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_void,
        arg4: ghostty_clipboard_request_e,
    ),
>;
pub type ghostty_runtime_write_clipboard_cb = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: ghostty_clipboard_e,
        arg3: *const ghostty_clipboard_content_s,
        arg4: usize,
        arg5: bool,
    ),
>;
pub type ghostty_runtime_close_surface_cb =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: bool)>;
pub type ghostty_runtime_action_cb = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: ghostty_app_t,
        arg2: ghostty_target_s,
        arg3: ghostty_action_s,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_runtime_config_s {
    pub userdata: *mut ::std::os::raw::c_void,
    pub supports_selection_clipboard: bool,
    pub wakeup_cb: ghostty_runtime_wakeup_cb,
    pub action_cb: ghostty_runtime_action_cb,
    pub read_clipboard_cb: ghostty_runtime_read_clipboard_cb,
    pub confirm_read_clipboard_cb: ghostty_runtime_confirm_read_clipboard_cb,
    pub write_clipboard_cb: ghostty_runtime_write_clipboard_cb,
    pub close_surface_cb: ghostty_runtime_close_surface_cb,
}
pub const ghostty_ipc_target_tag_e_GHOSTTY_IPC_TARGET_CLASS: ghostty_ipc_target_tag_e = 0;
pub const ghostty_ipc_target_tag_e_GHOSTTY_IPC_TARGET_DETECT: ghostty_ipc_target_tag_e = 1;
pub type ghostty_ipc_target_tag_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_ipc_target_u {
    pub klass: *mut ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ghostty_ipc_action_new_window_s {
    pub arguments: *mut *const ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ghostty_ipc_action_u {
    pub new_window: ghostty_ipc_action_new_window_s,
}
pub const ghostty_ipc_action_tag_e_GHOSTTY_IPC_ACTION_NEW_WINDOW: ghostty_ipc_action_tag_e = 0;
pub type ghostty_ipc_action_tag_e = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn ghostty_init(
        arg1: usize,
        arg2: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ghostty_cli_try_action();
}
unsafe extern "C" {
    pub fn ghostty_info() -> ghostty_info_s;
}
unsafe extern "C" {
    pub fn ghostty_translate(arg1: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ghostty_string_free(arg1: ghostty_string_s);
}
unsafe extern "C" {
    pub fn ghostty_config_new() -> ghostty_config_t;
}
unsafe extern "C" {
    pub fn ghostty_config_free(arg1: ghostty_config_t);
}
unsafe extern "C" {
    pub fn ghostty_config_clone(arg1: ghostty_config_t) -> ghostty_config_t;
}
unsafe extern "C" {
    pub fn ghostty_config_load_cli_args(arg1: ghostty_config_t);
}
unsafe extern "C" {
    pub fn ghostty_config_load_file(arg1: ghostty_config_t, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn ghostty_config_load_default_files(arg1: ghostty_config_t);
}
unsafe extern "C" {
    pub fn ghostty_config_load_recursive_files(arg1: ghostty_config_t);
}
unsafe extern "C" {
    pub fn ghostty_config_finalize(arg1: ghostty_config_t);
}
unsafe extern "C" {
    pub fn ghostty_config_get(
        arg1: ghostty_config_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: *const ::std::os::raw::c_char,
        arg4: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_config_trigger(
        arg1: ghostty_config_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
    ) -> ghostty_input_trigger_s;
}
unsafe extern "C" {
    pub fn ghostty_config_diagnostics_count(arg1: ghostty_config_t) -> u32;
}
unsafe extern "C" {
    pub fn ghostty_config_get_diagnostic(arg1: ghostty_config_t, arg2: u32)
        -> ghostty_diagnostic_s;
}
unsafe extern "C" {
    pub fn ghostty_config_open_path() -> ghostty_string_s;
}
unsafe extern "C" {
    pub fn ghostty_app_new(
        arg1: *const ghostty_runtime_config_s,
        arg2: ghostty_config_t,
    ) -> ghostty_app_t;
}
unsafe extern "C" {
    pub fn ghostty_app_free(arg1: ghostty_app_t);
}
unsafe extern "C" {
    pub fn ghostty_app_tick(arg1: ghostty_app_t);
}
unsafe extern "C" {
    pub fn ghostty_app_userdata(arg1: ghostty_app_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn ghostty_app_set_focus(arg1: ghostty_app_t, arg2: bool);
}
unsafe extern "C" {
    pub fn ghostty_app_key(arg1: ghostty_app_t, arg2: ghostty_input_key_s) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_app_key_is_binding(arg1: ghostty_app_t, arg2: ghostty_input_key_s) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_app_keyboard_changed(arg1: ghostty_app_t);
}
unsafe extern "C" {
    pub fn ghostty_app_open_config(arg1: ghostty_app_t);
}
unsafe extern "C" {
    pub fn ghostty_app_update_config(arg1: ghostty_app_t, arg2: ghostty_config_t);
}
unsafe extern "C" {
    pub fn ghostty_app_needs_confirm_quit(arg1: ghostty_app_t) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_app_has_global_keybinds(arg1: ghostty_app_t) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_app_set_color_scheme(arg1: ghostty_app_t, arg2: ghostty_color_scheme_e);
}
unsafe extern "C" {
    pub fn ghostty_surface_config_new() -> ghostty_surface_config_s;
}
unsafe extern "C" {
    pub fn ghostty_surface_new(
        arg1: ghostty_app_t,
        arg2: *const ghostty_surface_config_s,
    ) -> ghostty_surface_t;
}
unsafe extern "C" {
    pub fn ghostty_surface_free(arg1: ghostty_surface_t);
}
unsafe extern "C" {
    pub fn ghostty_surface_userdata(arg1: ghostty_surface_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn ghostty_surface_app(arg1: ghostty_surface_t) -> ghostty_app_t;
}
unsafe extern "C" {
    pub fn ghostty_surface_inherited_config(
        arg1: ghostty_surface_t,
        arg2: ghostty_surface_context_e,
    ) -> ghostty_surface_config_s;
}
unsafe extern "C" {
    pub fn ghostty_surface_update_config(arg1: ghostty_surface_t, arg2: ghostty_config_t);
}
unsafe extern "C" {
    pub fn ghostty_surface_needs_confirm_quit(arg1: ghostty_surface_t) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_process_exited(arg1: ghostty_surface_t) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_refresh(arg1: ghostty_surface_t);
}
unsafe extern "C" {
    pub fn ghostty_surface_draw(arg1: ghostty_surface_t);
}
unsafe extern "C" {
    pub fn ghostty_surface_set_content_scale(arg1: ghostty_surface_t, arg2: f64, arg3: f64);
}
unsafe extern "C" {
    pub fn ghostty_surface_set_focus(arg1: ghostty_surface_t, arg2: bool);
}
unsafe extern "C" {
    pub fn ghostty_surface_set_occlusion(arg1: ghostty_surface_t, arg2: bool);
}
unsafe extern "C" {
    pub fn ghostty_surface_set_size(arg1: ghostty_surface_t, arg2: u32, arg3: u32);
}
unsafe extern "C" {
    pub fn ghostty_surface_size(arg1: ghostty_surface_t) -> ghostty_surface_size_s;
}
unsafe extern "C" {
    pub fn ghostty_surface_set_color_scheme(arg1: ghostty_surface_t, arg2: ghostty_color_scheme_e);
}
unsafe extern "C" {
    pub fn ghostty_surface_key_translation_mods(
        arg1: ghostty_surface_t,
        arg2: ghostty_input_mods_e,
    ) -> ghostty_input_mods_e;
}
unsafe extern "C" {
    pub fn ghostty_surface_key(arg1: ghostty_surface_t, arg2: ghostty_input_key_s) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_key_is_binding(
        arg1: ghostty_surface_t,
        arg2: ghostty_input_key_s,
        arg3: *mut ghostty_binding_flags_e,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_text(
        arg1: ghostty_surface_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
    );
}
unsafe extern "C" {
    pub fn ghostty_surface_preedit(
        arg1: ghostty_surface_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
    );
}
unsafe extern "C" {
    pub fn ghostty_surface_mouse_captured(arg1: ghostty_surface_t) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_mouse_button(
        arg1: ghostty_surface_t,
        arg2: ghostty_input_mouse_state_e,
        arg3: ghostty_input_mouse_button_e,
        arg4: ghostty_input_mods_e,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_mouse_pos(
        arg1: ghostty_surface_t,
        arg2: f64,
        arg3: f64,
        arg4: ghostty_input_mods_e,
    );
}
unsafe extern "C" {
    pub fn ghostty_surface_mouse_scroll(
        arg1: ghostty_surface_t,
        arg2: f64,
        arg3: f64,
        arg4: ghostty_input_scroll_mods_t,
    );
}
unsafe extern "C" {
    pub fn ghostty_surface_mouse_pressure(arg1: ghostty_surface_t, arg2: u32, arg3: f64);
}
unsafe extern "C" {
    pub fn ghostty_surface_ime_point(
        arg1: ghostty_surface_t,
        arg2: *mut f64,
        arg3: *mut f64,
        arg4: *mut f64,
        arg5: *mut f64,
    );
}
unsafe extern "C" {
    pub fn ghostty_surface_request_close(arg1: ghostty_surface_t);
}
unsafe extern "C" {
    pub fn ghostty_surface_split(arg1: ghostty_surface_t, arg2: ghostty_action_split_direction_e);
}
unsafe extern "C" {
    pub fn ghostty_surface_split_focus(arg1: ghostty_surface_t, arg2: ghostty_action_goto_split_e);
}
unsafe extern "C" {
    pub fn ghostty_surface_split_resize(
        arg1: ghostty_surface_t,
        arg2: ghostty_action_resize_split_direction_e,
        arg3: u16,
    );
}
unsafe extern "C" {
    pub fn ghostty_surface_split_equalize(arg1: ghostty_surface_t);
}
unsafe extern "C" {
    pub fn ghostty_surface_binding_action(
        arg1: ghostty_surface_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_complete_clipboard_request(
        arg1: ghostty_surface_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_void,
        arg4: bool,
    );
}
unsafe extern "C" {
    pub fn ghostty_surface_has_selection(arg1: ghostty_surface_t) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_read_selection(
        arg1: ghostty_surface_t,
        arg2: *mut ghostty_text_s,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_read_text(
        arg1: ghostty_surface_t,
        arg2: ghostty_selection_s,
        arg3: *mut ghostty_text_s,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_free_text(arg1: ghostty_surface_t, arg2: *mut ghostty_text_s);
}
unsafe extern "C" {
    pub fn ghostty_surface_set_display_id(arg1: ghostty_surface_t, arg2: u32);
}
unsafe extern "C" {
    pub fn ghostty_surface_quicklook_font(arg1: ghostty_surface_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn ghostty_surface_quicklook_word(
        arg1: ghostty_surface_t,
        arg2: *mut ghostty_text_s,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_surface_inspector(arg1: ghostty_surface_t) -> ghostty_inspector_t;
}
unsafe extern "C" {
    pub fn ghostty_inspector_free(arg1: ghostty_surface_t);
}
unsafe extern "C" {
    pub fn ghostty_inspector_set_focus(arg1: ghostty_inspector_t, arg2: bool);
}
unsafe extern "C" {
    pub fn ghostty_inspector_set_content_scale(arg1: ghostty_inspector_t, arg2: f64, arg3: f64);
}
unsafe extern "C" {
    pub fn ghostty_inspector_set_size(arg1: ghostty_inspector_t, arg2: u32, arg3: u32);
}
unsafe extern "C" {
    pub fn ghostty_inspector_mouse_button(
        arg1: ghostty_inspector_t,
        arg2: ghostty_input_mouse_state_e,
        arg3: ghostty_input_mouse_button_e,
        arg4: ghostty_input_mods_e,
    );
}
unsafe extern "C" {
    pub fn ghostty_inspector_mouse_pos(arg1: ghostty_inspector_t, arg2: f64, arg3: f64);
}
unsafe extern "C" {
    pub fn ghostty_inspector_mouse_scroll(
        arg1: ghostty_inspector_t,
        arg2: f64,
        arg3: f64,
        arg4: ghostty_input_scroll_mods_t,
    );
}
unsafe extern "C" {
    pub fn ghostty_inspector_key(
        arg1: ghostty_inspector_t,
        arg2: ghostty_input_action_e,
        arg3: ghostty_input_key_e,
        arg4: ghostty_input_mods_e,
    );
}
unsafe extern "C" {
    pub fn ghostty_inspector_text(arg1: ghostty_inspector_t, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn ghostty_inspector_metal_init(
        arg1: ghostty_inspector_t,
        arg2: *mut ::std::os::raw::c_void,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_inspector_metal_render(
        arg1: ghostty_inspector_t,
        arg2: *mut ::std::os::raw::c_void,
        arg3: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ghostty_inspector_metal_shutdown(arg1: ghostty_inspector_t) -> bool;
}
unsafe extern "C" {
    pub fn ghostty_set_window_background_blur(
        arg1: ghostty_app_t,
        arg2: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn ghostty_benchmark_cli(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
    ) -> bool;
}
